const COUNTS = {
  "aho_corasick": 3,
  "bellman_ford": 6,
  "bfs_dfs": 349,
  "binary_exp": 33,
  "binary_search": 222,
  "binary_search_on_answer": 26,
  "bitwise": 252,
  "bridges": 17,
  "burnside_polya": 3,
  "centroid": 7,
  "counting": 1420,
  "dijkstra": 43,
  "dinic": 18,
  "dp": 658,
  "dp_bitmask": 40,
  "dp_count": 375,
  "dp_dag": 76,
  "dp_digit": 45,
  "dp_knapsack": 26,
  "dp_lcs": 14,
  "dp_lis": 27,
  "dp_reroot": 6,
  "dp_tree": 106,
  "dsu": 107,
  "euler": 18,
  "fenwick": 49,
  "fft": 84,
  "flows": 40,
  "floyd_warshall": 12,
  "ford_fulkerson": 1,
  "game_theory": 155,
  "geometry": 287,
  "gf": 83,
  "graph": 1238,
  "graph_games": 70,
  "greedy": 258,
  "hamiltonian": 8,
  "heap": 82,
  "hld": 10,
  "hopcroft_karp": 2,
  "hungarian": 1,
  "inclusion_exclusion": 88,
  "interactive": 21,
  "inversions": 58,
  "kmp": 9,
  "lca": 34,
  "lp": 8,
  "matching": 59,
  "mex": 19,
  "min_cost_flow": 8,
  "minmax": 13,
  "misc": 32,
  "mst": 48,
  "nim": 16,
  "nt": 760,
  "nt_crt": 9,
  "nt_diophantine": 4,
  "nt_divisibility": 372,
  "nt_factorization": 27,
  "nt_functions": 28,
  "nt_gcd": 100,
  "nt_lcm": 26,
  "nt_mobius": 7,
  "nt_modular": 271,
  "nt_mult_order": 2,
  "nt_num_div": 18,
  "nt_prim_roots": 7,
  "nt_primes": 112,
  "nt_totient": 6,
  "nt_uf": 1,
  "other": 0,
  "pigeonhole": 15,
  "practice": 3546,
  "prefix_sum": 208,
  "probability": 163,
  "range": 373,
  "scc": 19,
  "segment_tree": 161,
  "shortest_path": 109,
  "sorting": 797,
  "sparse_table": 10,
  "splay": 1,
  "sprague_grundy": 12,
  "sqrt_decomposition": 2,
  "sqrt_tree": 2,
  "stacks_queues": 37,
  "strings": 155,
  "subarrays_subsequences": 312,
  "subsets": 156,
  "suffix_array": 10,
  "suffix_tree": 0,
  "tarjan": 1,
  "topo": 19,
  "tree": 330,
  "trie": 23,
  "two_pointers": 74,
  "yfast": 1
};

document.querySelectorAll(".cat-count, .cat-count-badge").forEach(el => {
  const href = el.dataset.href;
  if (!href) return;
  const key = href.replace(".html", "");
  const count = COUNTS[key];
  if (count !== undefined) el.textContent = count;
});
