const COUNTS = {
  "aho_corasick": 3,
  "bellman_ford": 6,
  "bfs_dfs": 334,
  "binary_exp": 32,
  "binary_search": 310,
  "binary_search_on_answer": 42,
  "bitwise": 198,
  "bridges": 17,
  "burnside_polya": 3,
  "centroid": 6,
  "counting": 1173,
  "dijkstra": 42,
  "dinic": 17,
  "dp": 647,
  "dp_bitmask": 19,
  "dp_count": 362,
  "dp_dag": 44,
  "dp_knapsack": 15,
  "dp_lcs": 13,
  "dp_lis": 26,
  "dp_reroot": 5,
  "dp_tree": 101,
  "dsu": 87,
  "euler": 15,
  "fenwick": 45,
  "fft": 80,
  "flows": 38,
  "floyd_warshall": 12,
  "ford_fulkerson": 1,
  "game_theory": 105,
  "geometry": 220,
  "gf": 80,
  "graph": 1099,
  "graph_games": 49,
  "greedy": 149,
  "hamiltonian": 7,
  "heap": 77,
  "hld": 9,
  "hopcroft_karp": 2,
  "hungarian": 1,
  "inclusion_exclusion": 85,
  "interactive": 19,
  "inversions": 54,
  "kmp": 9,
  "lca": 30,
  "lp": 7,
  "matching": 56,
  "mex": 18,
  "min_cost_flow": 8,
  "minmax": 12,
  "misc": 30,
  "mst": 42,
  "nim": 14,
  "nt": 815,
  "nt_crt": 9,
  "nt_diophantine": 2,
  "nt_divisibility": 327,
  "nt_factorization": 27,
  "nt_functions": 27,
  "nt_gcd": 83,
  "nt_lcm": 26,
  "nt_mobius": 6,
  "nt_modular": 262,
  "nt_mult_order": 2,
  "nt_num_div": 17,
  "nt_prim_roots": 7,
  "nt_primes": 111,
  "nt_totient": 6,
  "nt_uf": 1,
  "other": 0,
  "pigeonhole": 15,
  "prefix_sum": 194,
  "probability": 137,
  "range": 349,
  "scc": 15,
  "segment_tree": 151,
  "shortest_path": 97,
  "sorting": 911,
  "sparse_table": 9,
  "splay": 1,
  "sprague_grundy": 11,
  "sqrt_decomposition": 2,
  "sqrt_tree": 2,
  "stacks_queues": 199,
  "strings": 208,
  "subarrays_subsequences": 244,
  "subsets": 128,
  "suffix_array": 10,
  "suffix_tree": 0,
  "tarjan": 1,
  "topo": 19,
  "tree": 307,
  "trie": 114,
  "two_pointers": 67,
  "yfast": 1
};

document.querySelectorAll(".cat-count, .cat-count-badge").forEach(el => {
  const href = el.dataset.href;
  if (!href) return;
  const key = href.replace(".html", "");
  const count = COUNTS[key];
  if (count !== undefined) el.textContent = count;
});
