const COUNTS = {
  "aho_corasick": 3,
  "bellman_ford": 6,
  "bfs_dfs": 341,
  "binary_exp": 32,
  "binary_search": 210,
  "binary_search_on_answer": 25,
  "bitwise": 237,
  "bridges": 17,
  "burnside_polya": 3,
  "centroid": 6,
  "counting": 1360,
  "dijkstra": 42,
  "dinic": 17,
  "dp": 685,
  "dp_bitmask": 40,
  "dp_count": 364,
  "dp_dag": 76,
  "dp_digit": 39,
  "dp_knapsack": 25,
  "dp_lcs": 14,
  "dp_lis": 26,
  "dp_reroot": 5,
  "dp_tree": 104,
  "dsu": 104,
  "euler": 17,
  "fenwick": 45,
  "fft": 80,
  "flows": 38,
  "floyd_warshall": 12,
  "ford_fulkerson": 1,
  "game_theory": 149,
  "geometry": 277,
  "gf": 104,
  "graph": 1192,
  "graph_games": 67,
  "greedy": 244,
  "hamiltonian": 8,
  "heap": 78,
  "hld": 9,
  "hopcroft_karp": 2,
  "hungarian": 1,
  "inclusion_exclusion": 85,
  "interactive": 19,
  "inversions": 54,
  "kmp": 9,
  "lca": 32,
  "lp": 7,
  "matching": 56,
  "mex": 18,
  "min_cost_flow": 8,
  "minmax": 12,
  "misc": 30,
  "mst": 44,
  "nim": 15,
  "nt": 731,
  "nt_crt": 9,
  "nt_diophantine": 3,
  "nt_divisibility": 361,
  "nt_factorization": 27,
  "nt_functions": 27,
  "nt_gcd": 96,
  "nt_lcm": 26,
  "nt_mobius": 6,
  "nt_modular": 264,
  "nt_mult_order": 2,
  "nt_num_div": 17,
  "nt_prim_roots": 7,
  "nt_primes": 111,
  "nt_totient": 6,
  "nt_uf": 1,
  "other": 0,
  "pigeonhole": 15,
  "practice": 3546,
  "prefix_sum": 197,
  "probability": 154,
  "range": 353,
  "scc": 19,
  "segment_tree": 151,
  "shortest_path": 108,
  "sorting": 764,
  "sparse_table": 9,
  "splay": 1,
  "sprague_grundy": 12,
  "sqrt_decomposition": 2,
  "sqrt_tree": 2,
  "stacks_queues": 35,
  "strings": 150,
  "subarrays_subsequences": 300,
  "subsets": 149,
  "suffix_array": 10,
  "suffix_tree": 0,
  "tarjan": 1,
  "topo": 19,
  "tree": 317,
  "trie": 23,
  "two_pointers": 67,
  "yfast": 1
};

document.querySelectorAll(".cat-count, .cat-count-badge").forEach(el => {
  const href = el.dataset.href;
  if (!href) return;
  const key = href.replace(".html", "");
  const count = COUNTS[key];
  if (count !== undefined) el.textContent = count;
});
